# Generated by Django 4.2.14 on 2025-02-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='检测日期')),
                ('quality_indicators', models.JSONField(verbose_name='质量指标')),
                ('analysis_result', models.TextField(verbose_name='分析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '质量分析',
                'verbose_name_plural': '质量分析',
                'db_table': 'quality_analysis',
            },
        ),
        migrations.CreateModel(
            name='SalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销售数量')),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='销售金额')),
                ('customer_count', models.IntegerField(default=0, verbose_name='购买人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '销售统计',
                'verbose_name_plural': '销售统计',
                'db_table': 'sales_statistics',
            },
        ),
        migrations.CreateModel(
            name='TracingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('scan_count', models.IntegerField(default=0, verbose_name='扫码次数')),
                ('query_count', models.IntegerField(default=0, verbose_name='查询次数')),
                ('region', models.CharField(max_length=100, verbose_name='查询地区')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '追溯统计',
                'verbose_name_plural': '追溯统计',
                'db_table': 'tracing_statistics',
            },
        ),
    ]
