# Generated by Django 4.2.14 on 2025-02-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_analysis', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracingstatistics',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracing_statistics', to='products.batch', verbose_name='商品批次'),
        ),
        migrations.AddField(
            model_name='salesstatistics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_statistics', to='products.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='qualityanalysis',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_analysis', to='products.batch', verbose_name='商品批次'),
        ),
    ]
