# Generated by Django 4.2.14 on 2025-02-03 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityanalysis',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='检测员'),
        ),
        migrations.AlterUniqueTogether(
            name='tracingstatistics',
            unique_together={('batch', 'date', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='salesstatistics',
            unique_together={('product', 'date')},
        ),
    ]
