# Generated by Django 4.2.14 on 2025-02-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='键')),
                ('value', models.JSONField(verbose_name='值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仪表盘设置',
                'verbose_name_plural': '仪表盘设置',
                'db_table': 'dashboard_setting',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.CharField(choices=[('warning', '预警'), ('system', '系统'), ('task', '任务')], max_length=20, verbose_name='类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知消息',
                'verbose_name_plural': '通知消息',
                'db_table': 'dashboard_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.CharField(choices=[('stock', '库存不足'), ('expiry', '即将过期'), ('quality', '质量问题'), ('system', '系统异常')], max_length=20, verbose_name='类型')),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], max_length=10, verbose_name='级别')),
                ('target', models.CharField(blank=True, max_length=100, verbose_name='预警对象')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统预警',
                'verbose_name_plural': '系统预警',
                'db_table': 'dashboard_warning',
                'ordering': ['-created_at'],
            },
        ),
    ]
