# Generated by Django 4.2.14 on 2025-02-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='type',
            field=models.CharField(choices=[('stock', '库存不足'), ('expiry', '即将过期'), ('quality', '质量问题'), ('system', '系统异常')], default='system', max_length=20, verbose_name='类型'),
        ),
    ]
