# Generated by Django 4.2.14 on 2025-02-03 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='仓库管理员'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='products.inventory', verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_info', to='products.batch', verbose_name='批次'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='父分类'),
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='商品'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='batch_quantity_non_negative'),
        ),
    ]
