# Generated by Django 4.2.14 on 2025-02-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': '批次', 'verbose_name_plural': '批次'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='批次号'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('active', '正常'), ('sold_out', '售罄'), ('expired', '过期'), ('disabled', '停用')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterModelTable(
            name='batch',
            table='batch',
        ),
    ]
