# Generated by Django 4.2.14 on 2025-02-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('storage', '入库'), ('delivery', '出库'), ('transport', '运输')], max_length=20, verbose_name='记录类型')),
                ('from_location', models.CharField(max_length=200, verbose_name='起始位置')),
                ('to_location', models.CharField(max_length=200, verbose_name='目标位置')),
                ('carrier', models.CharField(blank=True, max_length=100, null=True, verbose_name='承运商')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='运单号')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('exception', '异常')], default='pending', max_length=20, verbose_name='状态')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True, verbose_name='预计到达时间')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='实际到达时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物流记录',
                'verbose_name_plural': '物流记录',
                'db_table': 'logistics_record',
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_materials', models.JSONField(verbose_name='原材料信息')),
                ('production_date', models.DateTimeField(db_index=True, verbose_name='生产时间')),
                ('quality_check', models.JSONField(verbose_name='质检信息')),
                ('production_line', models.CharField(max_length=50, verbose_name='生产线')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='生产温度')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='生产环境湿度')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '生产记录',
                'verbose_name_plural': '生产记录',
                'db_table': 'production_record',
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总金额')),
                ('payment_method', models.CharField(max_length=50, verbose_name='支付方式')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='交易编号')),
                ('sale_date', models.DateTimeField(verbose_name='销售时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='products.batch', verbose_name='商品批次')),
            ],
            options={
                'verbose_name': '销售记录',
                'verbose_name_plural': '销售记录',
                'db_table': 'sales_record',
            },
        ),
    ]
