# Generated by Django 4.2.14 on 2025-02-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='customer',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='customer_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客户地址'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='customer_name',
            field=models.CharField(default=1, max_length=100, verbose_name='客户名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='客户电话'),
        ),
    ]
