# Generated by Django 4.2.14 on 2025-02-05 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_batch_options_alter_batch_batch_number_and_more'),
        ('tracing', '0003_remove_salesrecord_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticsrecord',
            name='actual_arrival',
        ),
        migrations.RemoveField(
            model_name='logisticsrecord',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='logisticsrecord',
            name='estimated_arrival',
        ),
        migrations.RemoveField(
            model_name='logisticsrecord',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='logisticsrecord',
            name='tracking_number',
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_records', to='products.batch'),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='from_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='record_type',
            field=models.CharField(choices=[('storage', '入库'), ('delivery', '出库'), ('transport', '运输中')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='to_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logisticsrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
