# Generated by Django 4.2.14 on 2025-02-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='公司名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('user', '普通用户')], default='user', max_length=20, verbose_name='用户角色'),
        ),
    ]
