# Generated by Django 4.2.7 on 2025-03-19 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('business_license', models.CharField(blank=True, max_length=50, verbose_name='营业执照号')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='原材料名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='原材料编码')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='规格')),
                ('origin', models.CharField(max_length=100, verbose_name='产地')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '原材料',
                'verbose_name_plural': '原材料',
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批次号')),
                ('production_date', models.DateField(verbose_name='生产日期')),
                ('expiry_date', models.DateField(verbose_name='有效期')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本价')),
                ('quality_certificate', models.CharField(blank=True, max_length=100, verbose_name='质量证书编号')),
                ('status', models.CharField(choices=[('in_storage', '在库'), ('used', '已使用'), ('expired', '已过期'), ('returned', '已退货')], default='in_storage', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='materials.material', verbose_name='原材料')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_batches', to='materials.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '原材料批次',
                'verbose_name_plural': '原材料批次',
                'db_table': 'material_batch',
                'unique_together': {('material', 'batch_number')},
            },
        ),
    ]
