# Generated by Django 4.2.7 on 2025-03-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='supplier',
        ),
        migrations.CreateModel(
            name='MaterialSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='采购价格')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='是否首选供应商')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_link', to='materials.material', verbose_name='原材料')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_link', to='materials.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '原材料供应商关联',
                'verbose_name_plural': '原材料供应商关联',
                'db_table': 'material_supplier',
                'unique_together': {('material', 'supplier')},
            },
        ),
    ]
